### ISSUE TITLE
1.21 Tracking

### ISSUE THREAD

**Issue by s-yh-china** [LeavesMC/Leaves#233]
### 描述你希望添加的功能。 Describe the feature you'd like.

- [x] Update 1.21
- [x] minecraft-old allowGrindstoneOverstacking
- [x] minecraft-old [MC-67](https://bugs.mojang.com/browse/MC-67)
- [x] minecraft-old disableGatewayPortalEntityTicking
- [x] leaves plugin (#271)
- [x] servux update
- [x] servux entity_data
- [ ] servux litematica
- [x] alternative-block-placement update
- [x] syncmatica
- [x] 1.21 Sound Suppression and Unbreakable Blocks ~~f**k mojang~~

### 其他 Other

If more features need to be rejoined, please comment on this issue

**Comment by neokoni** [comment]
进度落后purpur😱

**Comment by CharfyMonologue** [comment]
服务端1.21.1

**Comment by Bluemangoo** [comment]
.1?

**Comment by konsheng** [comment]
请问下大概什么时候可以支持呢

**Comment by Bluemangoo** [comment]
等到这个表上勾全打完才开始干活。

https://github.com/PaperMC/Paper/issues/10876

**Comment by MC-XiaoHei** [comment]
mixin plugin（心心念念

**Comment by hseermc** [comment]
粘液都能用1.21了，就差leaves力（开心

**Comment by rat233** [comment]
修正一个小小的语法错误：If more features need to be rejoined, please comment on this issue(

**Comment by SinsimitoCCMT** [comment]
就是说能不能放个SNAPSHOT版本尝尝鲜👉👈

**Comment by YuanYuanOwO** [comment]
> 就是说能不能放个SNAPSHOT版本尝尝鲜👉👈

https://github.com/LeavesMC/Leaves/actions  
actions快速尝鲜，使用时后果自负，记得备份

**Comment by MC-XiaoHei** [comment]
见到paper发版v姐突然开始发力（x

**Comment by MC-XiaoHei** [comment]
需要测试以保证没有功能缺失与恶行bug

**Comment by tingnainae** [comment]
paper1.21正式版出了欸，所以啥时候更新正式版

**Comment by LittleChest** [comment]
> paper1.21正式版出了欸，所以啥时候更新正式版

已经发正式版了
